### ISSUE TITLE
Redesign the page

### ISSUE THREAD

**Issue by rjsalvadorr** [rjsalvadorr/routinetrax#19]
# todo

- [x] improve color scheme and text --- use the colour palettes you've saved
- [x] simplify months view (no expand/collapse)
- [x] hide the "paper" dropdown
- [x] add more controls (remove habit, clear habits, copy last)

# design sketches

![IMG_20200712_163059](https://user-images.githubusercontent.com/6898647/87875585-4bb00a80-c9a0-11ea-96f3-7970a91a44f9.jpg)
![IMG_20200712_163107](https://user-images.githubusercontent.com/6898647/87875586-4c48a100-c9a0-11ea-9e30-f81e6b4bb79b.jpg)

**Comment by rjsalvadorr** [comment]
done!
